#!/bin/bash
echo "Testing environment"

MODLIST=$(module list 2>&1)
MODULESLOADED=$(echo -e "$MODLIST" | sed -e 's/)/\n/g' | awk 'NR>=3 {print $1}')

pgi=0
openmpi=0

for mod in $MODULESLOADED
do
  if [ "$mod" == "pgi/19.4" ] 
  then
      pgi=1
  fi
  if [ "$mod" == "openmpi/3.1.3/2019" ]
  then
      openmpi=1
  fi
done;

[ "$pgi" == "1" ] || echo "Please module load pgi/19.4" 
[ "$pgi" == "1" ] || exit 1

[ "$openmpi" == "1" ] || echo "Please module load openmpi/3.1.3/2019" 
[ "$openmpi" == "1" ] || exit 1

echo "Environment OK"
